name: Fetch COT Data Weekly

on:
  schedule:
    # Every Friday at 18:00 UTC (CFTC releases ~15:30 ET = ~20:30 UTC, this catches it)
    - cron: '0 18 * * 5'
  workflow_dispatch:  # Allows manual trigger from GitHub Actions tab

jobs:
  fetch-cot:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed to commit cot_data.json back to repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run COT fetch script
        run: python fetch_cot.py

      - name: Commit and push cot_data.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add cot_data.json
          git diff --staged --quiet || git commit -m "Auto-update COT data $(date +'%Y-%m-%d')"
          git push
